// code generated by thespian; DO NOT EDIT

package common

// MessageBatchMailbox is a mailbox for messages of type []Message.
type MessageBatchMailbox struct {
	// C is the bidirectional channel over which messages will be transferred.  If
	// this is not set in the mailbox, a fresh channel will be created automatically.
	C chan []Message
	// Disabled, if set to true, causes the mailbox to start life disabled.
	Disabled bool
}

// ApplyDefaults applies default settings to this MessageBatch, if
// the struct has its zero value.
func (mbox *MessageBatchMailbox) ApplyDefaults() {
	if mbox.C == nil {
		mbox.C = make(chan []Message, 10) // default channel size
	}
}

// Tx creates a MessageBatchTx for this mailbox
func (mbox *MessageBatchMailbox) Tx() MessageBatchTx {
	return MessageBatchTx{
		C: mbox.C,
	}
}

// Rx creates a MessageBatchRx for this mailbox
func (mbox *MessageBatchMailbox) Rx() MessageBatchRx {
	return MessageBatchRx{
		C:        mbox.C,
		Disabled: mbox.Disabled,
	}
}

// MessageBatchTx sends to a mailbox for messages of type []Message.
type MessageBatchTx struct {
	C chan<- []Message
}

// MessageBatchRx receives from a mailbox for messages of type []Message.
type MessageBatchRx struct {
	C <-chan []Message
	// Disabled, if set to true, will disable receipt of messages from this mailbox.
	Disabled bool
}

// Chan gets a channel for this mailbox, or nil if there is nothing to select from.
func (rx *MessageBatchRx) Chan() <-chan []Message {
	if rx.Disabled {
		return nil
	}
	return rx.C
}
